name: floating_bubbles
description: A Flutter Package for adding Floating bubbles on the Foreground to any Flutter widget.
version: 0.0.2
homepage: https://github.com/Poujhit/floating_bubbles
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  simple_animations: ^2.4.2 
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
