name: floating_bubbles
description: A Flutter Package for adding Floating bubbles on the Foreground to any Flutter widget.
version: 2.4.0
homepage: https://github.com/Poujhit/floating_bubbles
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  sa4_migration_kit: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
