name: floating_bubbles
description: A Flutter Package for adding Floating bubbles on the Foreground to any Flutter widget.
version: 2.0.0-nullsafety.5
homepage: https://github.com/Poujhit/floating_bubbles
environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  simple_animations: ^3.0.0-nullsafety.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
